name: Extract Project and Match Blocks from Trigger JSON

on:
  push:

jobs:
  extract-json:
    runs-on: ubuntu-latest
    steps:
      - uses: mongocaleb/jq-action@v2
      - name: Finding JSON files and store to output
        id: finding-files
        run: |
          cd ./triggers/
          echo "::set-output name=FILELIST::$(find . -name '*.json' -print)"
      - name: Iterate files and parse them
        run: |
          IFS="," read -a myarray <<< ${{ steps.finding-files.outputs.FILELIST }}
          for i in "${myarray[@]}"; do
            file_path=$(dirname "${i}")
            file_name=$(basename "${i}")
            cd file_path
            cat ./triggers/match_update.json | jq '.config.match'
          done
