name: Extract Project and Match Blocks from Trigger JSON

on:
  push:

jobs:
  extract-json:
    runs-on: ubuntu-latest
    steps:
      - uses: mongocaleb/jq-action@v2.3.0
      - uses: actions/checkout@v4
      - name: Finding JSON files and store to output
        id: finding-files
        run: |
          : # cd snippets/trigger-expressions
          echo "::set-output name=FILELIST::$(find snippets/trigger-expressions/*.json)"
      - name: Iterate files and parse them
        run: |
          : # ls
          IFS="," read -a myarray <<< ${{ steps.finding-files.outputs.FILELIST }}
          for i in "${{ steps.finding-files.outputs.FILELIST }}"; do
            echo "${i}"
            cat "${i}" | jq '.config.match'
          done
      