name: Remove Function Name Prefixes

on:
  push:
    branches:
      - development

jobs:
  build:
    name: remove prefixes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git pull origin development --rebase
          for file in $(find ./snippets/functions/  -type f -name '*.js'); do 
            if [[ "$file" == *"_"* ]];then
                justfile=$(basename -- "$file")
                justpath=$(dirname "$file")
                # echo $justfile
                justfile="${justfile#*_}"
                echo $justpath/$justfile
                mv -n $file $justpath/$justfile
            fi 
          done
          git add .
          git config --global user.email "caleb.thompson@mongodb.com"
          git config --global user.name "ActionBot"
          git commit -m 'test'
          git push -f
          git reset origin/development --soft
