name: Atlas Functions and Triggers Example Tests

on:
  workflow_run:
    workflows: [remove-function-prefix]
    types: [completed]
  pull_request:
    paths:
      - "snippets/**"

jobs:
  run-node-tests:
    name: Run Function and Trigger Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: tests/integration
        run: npm install
      - name: Test the Examples
        working-directory: tests/integration
        run: npm run test:ts