name: Update Commit Hash

on:
  pull_request:
    types: [closed]
    branches:
      - development  # Adjust branch name as needed

jobs:
  update_commit_hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get merge commit hash
        id: get_merge_commit_hash
        run: echo "::set-output name=merge_commit_hash::$(git show -s --format=%H ${{ github.event.pull_request.merge_commit_sha }})"

      - name: Update file with merge commit hash
        run: |
          sed -i 's/<!-- Commit Hash: .* -->/<!-- Commit Hash: ${{ steps.get_merge_commit_hash.outputs.merge_commit_hash }} -->/' manifest.md
          git config --global user.email "caleb.thompson@mongodb.com"
          git config --global user.name "ActionBot"
          git add manifest.json
          git commit --amend --no-edit
          git push --force
